import type { ModuleSchemaDef } from '@/lib/modules/types'

export const newsletterSchema: ModuleSchemaDef = {
  key: 'newsletter',
  name: { es: 'Newsletter / Suscripción', en: 'Newsletter / Subscription' },
  description: {
    es: 'Formulario simple de suscripción por email.',
    en: 'Simple email subscription form.',
  },
  version: 1,
  fields: [
    {
      key: 'title',
      type: 'text',
      label: { es: 'Título', en: 'Title' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 100 },
      order: 1,
    },
    {
      key: 'subtitle',
      type: 'textarea',
      label: { es: 'Subtítulo', en: 'Subtitle' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 300 },
      order: 2,
    },
    {
      key: 'placeholder_email',
      type: 'text',
      label: { es: 'Placeholder del campo email', en: 'Email field placeholder' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 60 },
      order: 3,
    },
    {
      key: 'button_label',
      type: 'text',
      label: { es: 'Texto del botón', en: 'Button label' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 40 },
      order: 4,
    },
    {
      key: 'success_title',
      type: 'text',
      label: { es: 'Título de éxito', en: 'Success title' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 100 },
      order: 5,
    },
    {
      key: 'success_message',
      type: 'textarea',
      label: { es: 'Mensaje de éxito', en: 'Success message' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 300 },
      order: 6,
    },
    {
      key: 'privacy_text',
      type: 'text',
      label: { es: 'Texto de privacidad', en: 'Privacy text' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 200 },
      order: 7,
    },
  ],
}
