import type { ModuleSchemaDef } from '@/lib/modules/types'

export const socialProofSchema: ModuleSchemaDef = {
  key: 'social_proof',
  name: { es: 'Testimonios', en: 'Testimonials' },
  description: {
    es: 'Sección de testimonios de clientes con estrellas, fotos y cargos.',
    en: 'Customer testimonials section with stars, photos, and roles.',
  },
  version: 1,
  fields: [
    {
      key: 'title',
      type: 'text',
      label: { es: 'Título de la sección', en: 'Section title' },
      isMultilingual: true,
      required: true,
      validation: { minLength: 3, maxLength: 100 },
      order: 1,
    },
    {
      key: 'subtitle',
      type: 'textarea',
      label: { es: 'Subtítulo', en: 'Subtitle' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 300 },
      order: 2,
    },
    {
      key: 'testimonials',
      type: 'list',
      label: { es: 'Testimonios', en: 'Testimonials' },
      isMultilingual: false,
      required: true,
      order: 3,
      listItemSchema: [
        {
          key: 'id',
          type: 'text',
          label: { es: 'ID único', en: 'Unique ID' },
          isMultilingual: false,
          required: true,
        },
        {
          key: 'quote',
          type: 'textarea',
          label: { es: 'Testimonio', en: 'Testimonial' },
          isMultilingual: true,
          required: true,
          validation: { maxLength: 500 },
        },
        {
          key: 'authorName',
          type: 'text',
          label: { es: 'Nombre del autor', en: 'Author name' },
          isMultilingual: false,
          required: true,
          validation: { maxLength: 100 },
        },
        {
          key: 'authorRole',
          type: 'text',
          label: { es: 'Cargo / Rol', en: 'Role / Title' },
          isMultilingual: true,
          required: false,
          validation: { maxLength: 100 },
        },
        {
          key: 'authorAvatar',
          type: 'image',
          label: { es: 'Foto del autor', en: 'Author photo' },
          isMultilingual: false,
          required: false,
        },
        {
          key: 'rating',
          type: 'number',
          label: { es: 'Calificación (1–5)', en: 'Rating (1–5)' },
          isMultilingual: false,
          required: false,
          defaultValue: 5,
          validation: { min: 1, max: 5 },
        },
        {
          key: 'company',
          type: 'text',
          label: { es: 'Empresa', en: 'Company' },
          isMultilingual: false,
          required: false,
          validation: { maxLength: 100 },
        },
      ],
    },
    {
      key: 'layout',
      type: 'select',
      label: { es: 'Estilo visual', en: 'Visual style' },
      isMultilingual: false,
      required: false,
      defaultValue: 'carousel',
      selectOptions: [
        { value: 'carousel', label: { es: 'Carrusel', en: 'Carousel' } },
        { value: 'grid', label: { es: 'Cuadrícula', en: 'Grid' } },
        { value: 'masonry', label: { es: 'Masonry', en: 'Masonry' } },
      ],
      order: 4,
    },
  ],
}
