import type { ModuleSchemaDef } from '@/lib/modules/types'

export const offerFormSchema: ModuleSchemaDef = {
  key: 'offer_form',
  name: { es: 'Formulario de contacto', en: 'Contact Form' },
  description: {
    es: 'Formulario configurable para capturar leads y consultas.',
    en: 'Configurable form for capturing leads and inquiries.',
  },
  version: 1,
  fields: [
    {
      key: 'title',
      type: 'text',
      label: { es: 'Título del formulario', en: 'Form title' },
      description: {
        es: 'Título visible sobre el formulario.',
        en: 'Title displayed above the form.',
      },
      isMultilingual: true,
      required: true,
      validation: { minLength: 3, maxLength: 100 },
      order: 1,
    },
    {
      key: 'subtitle',
      type: 'text',
      label: { es: 'Subtítulo', en: 'Subtitle' },
      description: {
        es: 'Texto de apoyo bajo el título.',
        en: 'Supporting text below the title.',
      },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 200 },
      order: 2,
    },
    {
      key: 'fields',
      type: 'list',
      label: { es: 'Campos del formulario', en: 'Form fields' },
      description: {
        es: 'Lista de campos que aparecerán en el formulario.',
        en: 'List of fields that will appear in the form.',
      },
      isMultilingual: false,
      required: true,
      order: 3,
      listItemSchema: [
        {
          key: 'key',
          type: 'text',
          label: { es: 'Clave del campo', en: 'Field key' },
          isMultilingual: false,
          required: true,
        },
        {
          key: 'type',
          type: 'select',
          label: { es: 'Tipo de campo', en: 'Field type' },
          isMultilingual: false,
          required: true,
          selectOptions: [
            { value: 'text', label: { es: 'Texto', en: 'Text' } },
            { value: 'email', label: { es: 'Email', en: 'Email' } },
            { value: 'tel', label: { es: 'Teléfono', en: 'Phone' } },
            { value: 'textarea', label: { es: 'Área de texto', en: 'Textarea' } },
            { value: 'select', label: { es: 'Selector', en: 'Select' } },
          ],
        },
        {
          key: 'label',
          type: 'text',
          label: { es: 'Etiqueta', en: 'Label' },
          isMultilingual: true,
          required: true,
        },
        {
          key: 'placeholder',
          type: 'text',
          label: { es: 'Placeholder', en: 'Placeholder' },
          isMultilingual: true,
          required: false,
        },
        {
          key: 'required',
          type: 'boolean',
          label: { es: '¿Requerido?', en: 'Required?' },
          isMultilingual: false,
          required: false,
          defaultValue: false,
        },
      ],
    },
    {
      key: 'submitLabel',
      type: 'text',
      label: { es: 'Texto del botón de envío', en: 'Submit button text' },
      isMultilingual: true,
      required: true,
      validation: { maxLength: 60 },
      order: 4,
    },
    {
      key: 'successMessage',
      type: 'text',
      label: { es: 'Mensaje de éxito', en: 'Success message' },
      description: {
        es: 'Mensaje mostrado al usuario después de enviar el formulario exitosamente.',
        en: 'Message shown to the user after successfully submitting the form.',
      },
      isMultilingual: true,
      required: true,
      validation: { maxLength: 200 },
      order: 5,
    },
    {
      key: 'sourceModule',
      type: 'text',
      label: { es: 'Identificador de origen', en: 'Source identifier' },
      description: {
        es: 'Etiqueta interna para identificar de qué formulario proviene el lead.',
        en: 'Internal tag to identify which form the lead came from.',
      },
      isMultilingual: false,
      required: false,
      defaultValue: 'offer_form',
      order: 6,
    },
  ],
}
