import type { ModuleSchemaDef } from '@/lib/modules/types'

export const footerSchema: ModuleSchemaDef = {
  key: 'footer',
  name: { es: 'Pie de página', en: 'Footer' },
  description: {
    es: 'Pie de página con columnas de enlaces, redes sociales y copyright.',
    en: 'Footer with link columns, social media, and copyright.',
  },
  version: 1,
  fields: [
    {
      key: 'columns',
      type: 'list',
      label: { es: 'Columnas de enlaces', en: 'Link columns' },
      description: {
        es: 'Cada columna tiene un título y una lista de enlaces.',
        en: 'Each column has a title and a list of links.',
      },
      isMultilingual: false,
      required: false,
      order: 1,
      listItemSchema: [
        {
          key: 'title',
          type: 'text',
          label: { es: 'Título de columna', en: 'Column title' },
          isMultilingual: true,
          required: true,
        },
        {
          key: 'links',
          type: 'list',
          label: { es: 'Enlaces', en: 'Links' },
          isMultilingual: false,
          required: false,
          listItemSchema: [
            {
              key: 'label',
              type: 'text',
              label: { es: 'Texto del enlace', en: 'Link text' },
              isMultilingual: true,
              required: true,
            },
            {
              key: 'url',
              type: 'link',
              label: { es: 'URL', en: 'URL' },
              isMultilingual: false,
              required: true,
            },
          ],
        },
      ],
    },
    {
      key: 'copyright',
      type: 'text',
      label: { es: 'Texto de copyright', en: 'Copyright text' },
      isMultilingual: true,
      required: true,
      validation: { maxLength: 200 },
      order: 2,
    },
    {
      key: 'showSocialLinks',
      type: 'boolean',
      label: { es: 'Mostrar redes sociales', en: 'Show social links' },
      isMultilingual: false,
      required: false,
      defaultValue: true,
      order: 3,
    },
    {
      key: 'socialLinks.facebook',
      type: 'link',
      label: { es: 'Facebook URL', en: 'Facebook URL' },
      isMultilingual: false,
      required: false,
      group: 'social',
      order: 4,
    },
    {
      key: 'socialLinks.twitter',
      type: 'link',
      label: { es: 'Twitter/X URL', en: 'Twitter/X URL' },
      isMultilingual: false,
      required: false,
      group: 'social',
      order: 5,
    },
    {
      key: 'socialLinks.instagram',
      type: 'link',
      label: { es: 'Instagram URL', en: 'Instagram URL' },
      isMultilingual: false,
      required: false,
      group: 'social',
      order: 6,
    },
    {
      key: 'socialLinks.linkedin',
      type: 'link',
      label: { es: 'LinkedIn URL', en: 'LinkedIn URL' },
      isMultilingual: false,
      required: false,
      group: 'social',
      order: 7,
    },
    {
      key: 'socialLinks.youtube',
      type: 'link',
      label: { es: 'YouTube URL', en: 'YouTube URL' },
      isMultilingual: false,
      required: false,
      group: 'social',
      order: 8,
    },
    {
      key: 'legalLinks',
      type: 'list',
      label: { es: 'Enlaces legales', en: 'Legal links' },
      description: {
        es: 'Privacidad, términos, cookies, etc.',
        en: 'Privacy, terms, cookies, etc.',
      },
      isMultilingual: false,
      required: false,
      order: 9,
      listItemSchema: [
        {
          key: 'label',
          type: 'text',
          label: { es: 'Texto', en: 'Text' },
          isMultilingual: true,
          required: true,
        },
        {
          key: 'url',
          type: 'link',
          label: { es: 'URL', en: 'URL' },
          isMultilingual: false,
          required: true,
        },
      ],
    },
  ],
}
