import type { ModuleSchemaDef } from '@/lib/modules/types'

export const heroSchema: ModuleSchemaDef = {
  key: 'hero',
  name: { es: 'Hero', en: 'Hero' },
  description: {
    es: 'Sección principal con título, subtítulo, descripción y botones de acción.',
    en: 'Main hero section with title, subtitle, description, and call-to-action buttons.',
  },
  version: 1,
  fields: [
    {
      key: 'title',
      type: 'text',
      label: { es: 'Título principal', en: 'Main title' },
      description: {
        es: 'El título grande que verán tus visitantes primero.',
        en: 'The large title visitors see first.',
      },
      isMultilingual: true,
      required: true,
      validation: { minLength: 3, maxLength: 120 },
      order: 1,
    },
    {
      key: 'subtitle',
      type: 'text',
      label: { es: 'Subtítulo', en: 'Subtitle' },
      description: {
        es: 'Frase de apoyo bajo el título.',
        en: 'Supporting phrase below the title.',
      },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 200 },
      order: 2,
    },
    {
      key: 'description',
      type: 'textarea',
      label: { es: 'Descripción', en: 'Description' },
      description: {
        es: 'Texto opcional con más detalle.',
        en: 'Optional text with more detail.',
      },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 500 },
      order: 3,
    },
    {
      key: 'primaryButton.label',
      type: 'text',
      label: { es: 'Botón primario — texto', en: 'Primary button — text' },
      isMultilingual: true,
      required: false,
      group: 'buttons',
      order: 4,
    },
    {
      key: 'primaryButton.url',
      type: 'link',
      label: { es: 'Botón primario — URL', en: 'Primary button — URL' },
      isMultilingual: false,
      required: false,
      group: 'buttons',
      order: 5,
    },
    {
      key: 'primaryButton.variant',
      type: 'select',
      label: { es: 'Botón primario — variante', en: 'Primary button — variant' },
      isMultilingual: false,
      required: false,
      group: 'buttons',
      defaultValue: 'primary',
      selectOptions: [
        { value: 'primary', label: { es: 'Primario', en: 'Primary' } },
        { value: 'secondary', label: { es: 'Secundario', en: 'Secondary' } },
        { value: 'outline', label: { es: 'Contorno', en: 'Outline' } },
      ],
      order: 6,
    },
    {
      key: 'secondaryButton.label',
      type: 'text',
      label: { es: 'Botón secundario — texto', en: 'Secondary button — text' },
      isMultilingual: true,
      required: false,
      group: 'buttons',
      order: 7,
    },
    {
      key: 'secondaryButton.url',
      type: 'link',
      label: { es: 'Botón secundario — URL', en: 'Secondary button — URL' },
      isMultilingual: false,
      required: false,
      group: 'buttons',
      order: 8,
    },
    {
      key: 'backgroundImage',
      type: 'image',
      label: { es: 'Imagen de fondo', en: 'Background image' },
      isMultilingual: false,
      required: false,
      order: 9,
    },
    {
      key: 'backgroundVideo',
      type: 'link',
      label: { es: 'Video de fondo (URL)', en: 'Background video (URL)' },
      description: {
        es: 'URL directa a un archivo de video (.mp4, .webm).',
        en: 'Direct URL to a video file (.mp4, .webm).',
      },
      isMultilingual: false,
      required: false,
      order: 10,
    },
    {
      key: 'overlayOpacity',
      type: 'number',
      label: { es: 'Opacidad del overlay', en: 'Overlay opacity' },
      description: {
        es: 'Oscuridad del overlay sobre el fondo (0–1).',
        en: 'Darkness of the overlay on the background (0–1).',
      },
      isMultilingual: false,
      required: false,
      defaultValue: 0.5,
      validation: { min: 0, max: 1 },
      order: 11,
    },
    {
      key: 'layout',
      type: 'select',
      label: { es: 'Disposición', en: 'Layout' },
      isMultilingual: false,
      required: false,
      defaultValue: 'centered',
      selectOptions: [
        { value: 'centered', label: { es: 'Centrado', en: 'Centered' } },
        { value: 'left', label: { es: 'Izquierda', en: 'Left' } },
        { value: 'split', label: { es: 'Dividido', en: 'Split' } },
      ],
      order: 12,
    },
  ],
}
