import type { ModuleSchemaDef } from '@/lib/modules/types'

export const featuresGridSchema: ModuleSchemaDef = {
  key: 'features_grid',
  name: { es: 'Grid de características', en: 'Features Grid' },
  description: {
    es: 'Grid de características con iconos y descripciones.',
    en: 'Features grid with icons and descriptions.',
  },
  version: 1,
  fields: [
    {
      key: 'title',
      type: 'text',
      label: { es: 'Título (opcional)', en: 'Title (optional)' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 100 },
      order: 1,
    },
    {
      key: 'subtitle',
      type: 'text',
      label: { es: 'Subtítulo (opcional)', en: 'Subtitle (optional)' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 200 },
      order: 2,
    },
    {
      key: 'columns',
      type: 'select',
      label: { es: 'Número de columnas', en: 'Number of columns' },
      isMultilingual: false,
      required: false,
      defaultValue: '3',
      selectOptions: [
        { value: '2', label: { es: '2 columnas', en: '2 columns' } },
        { value: '3', label: { es: '3 columnas', en: '3 columns' } },
        { value: '4', label: { es: '4 columnas', en: '4 columns' } },
      ],
      order: 3,
    },
    {
      key: 'show_icon_background',
      type: 'boolean',
      label: { es: 'Mostrar fondo en iconos', en: 'Show icon background' },
      isMultilingual: false,
      required: false,
      defaultValue: true,
      order: 4,
    },
    {
      key: 'features',
      type: 'list',
      label: { es: 'Características', en: 'Features' },
      description: {
        es: 'Lista de características a mostrar.',
        en: 'List of features to display.',
      },
      isMultilingual: false,
      required: true,
      order: 5,
      listItemSchema: [
        {
          key: 'id',
          type: 'text',
          label: { es: 'ID único', en: 'Unique ID' },
          isMultilingual: false,
          required: true,
        },
        {
          key: 'icon',
          type: 'select',
          label: { es: 'Icono', en: 'Icon' },
          isMultilingual: false,
          required: true,
          selectOptions: [
            { value: 'zap', label: { es: 'Rayo', en: 'Zap' } },
            { value: 'shield', label: { es: 'Escudo', en: 'Shield' } },
            { value: 'star', label: { es: 'Estrella', en: 'Star' } },
            { value: 'check', label: { es: 'Verificación', en: 'Check' } },
            { value: 'rocket', label: { es: 'Cohete', en: 'Rocket' } },
            { value: 'heart', label: { es: 'Corazón', en: 'Heart' } },
            { value: 'globe', label: { es: 'Globo', en: 'Globe' } },
            { value: 'lock', label: { es: 'Candado', en: 'Lock' } },
            { value: 'chart', label: { es: 'Gráfico', en: 'Chart' } },
            { value: 'users', label: { es: 'Usuarios', en: 'Users' } },
            { value: 'settings', label: { es: 'Configuración', en: 'Settings' } },
            { value: 'cpu', label: { es: 'Procesador', en: 'CPU' } },
            { value: 'code', label: { es: 'Código', en: 'Code' } },
            { value: 'database', label: { es: 'Base de datos', en: 'Database' } },
            { value: 'cloud', label: { es: 'Nube', en: 'Cloud' } },
            { value: 'mobile', label: { es: 'Móvil', en: 'Mobile' } },
            { value: 'mail', label: { es: 'Correo', en: 'Mail' } },
            { value: 'bell', label: { es: 'Campana', en: 'Bell' } },
          ],
        },
        {
          key: 'title',
          type: 'text',
          label: { es: 'Título', en: 'Title' },
          isMultilingual: true,
          required: true,
          validation: { maxLength: 80 },
        },
        {
          key: 'description',
          type: 'textarea',
          label: { es: 'Descripción', en: 'Description' },
          isMultilingual: true,
          required: true,
          validation: { maxLength: 300 },
        },
        {
          key: 'color',
          type: 'color',
          label: { es: 'Color personalizado (opcional)', en: 'Custom color (optional)' },
          isMultilingual: false,
          required: false,
        },
      ],
    },
  ],
}
