import type { ModuleSchemaDef } from '@/lib/modules/types'

export const mapLocationSchema: ModuleSchemaDef = {
  key: 'map_location',
  name: { es: 'Mapa y ubicación', en: 'Map & location' },
  description: {
    es: 'Mapa embebido de Google Maps con panel de información de contacto y horarios.',
    en: 'Embedded Google Maps iframe with contact info panel and business hours.',
  },
  version: 1,
  fields: [
    {
      key: 'title',
      type: 'text',
      label: { es: 'Título (opcional)', en: 'Title (optional)' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 100 },
      order: 1,
    },
    {
      key: 'address',
      type: 'textarea',
      label: { es: 'Dirección', en: 'Address' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 300 },
      order: 2,
    },
    {
      key: 'map_embed_url',
      type: 'text',
      label: { es: 'URL de embed de Google Maps', en: 'Google Maps embed URL' },
      description: {
        es: 'Copia la URL desde Google Maps > Compartir > Insertar un mapa.',
        en: 'Copy the URL from Google Maps > Share > Embed a map.',
      },
      isMultilingual: false,
      required: false,
      order: 3,
    },
    {
      key: 'aspect_ratio',
      type: 'select',
      label: { es: 'Relación de aspecto del mapa', en: 'Map aspect ratio' },
      isMultilingual: false,
      required: false,
      defaultValue: '16/9',
      selectOptions: [
        { value: '16/9', label: { es: '16:9 (panorámico)', en: '16:9 (widescreen)' } },
        { value: '4/3', label: { es: '4:3 (estándar)', en: '4:3 (standard)' } },
        { value: '1/1', label: { es: '1:1 (cuadrado)', en: '1:1 (square)' } },
      ],
      order: 4,
    },
    {
      key: 'show_info_panel',
      type: 'boolean',
      label: { es: 'Mostrar panel de información', en: 'Show info panel' },
      description: {
        es: 'Si está activo, muestra dirección, teléfono, email y horarios al lado del mapa.',
        en: 'When enabled, shows address, phone, email, and hours next to the map.',
      },
      isMultilingual: false,
      required: false,
      defaultValue: true,
      order: 5,
    },
    {
      key: 'phone',
      type: 'text',
      label: { es: 'Teléfono', en: 'Phone' },
      isMultilingual: false,
      required: false,
      validation: { maxLength: 30 },
      order: 6,
    },
    {
      key: 'email',
      type: 'text',
      label: { es: 'Email de contacto', en: 'Contact email' },
      isMultilingual: false,
      required: false,
      validation: { maxLength: 100 },
      order: 7,
    },
    {
      key: 'hours',
      type: 'list',
      label: { es: 'Horarios de atención', en: 'Business hours' },
      isMultilingual: false,
      required: false,
      order: 8,
      listItemSchema: [
        {
          key: 'day',
          type: 'text',
          label: { es: 'Día(s)', en: 'Day(s)' },
          isMultilingual: true,
          required: true,
        },
        {
          key: 'hours',
          type: 'text',
          label: { es: 'Horario (ej: 9:00 – 18:00)', en: 'Hours (e.g., 9:00 – 18:00)' },
          isMultilingual: false,
          required: false,
        },
        {
          key: 'closed',
          type: 'boolean',
          label: { es: '¿Cerrado?', en: 'Closed?' },
          isMultilingual: false,
          required: false,
          defaultValue: false,
        },
      ],
    },
  ],
}
