import type { ModuleSchemaDef } from '@/lib/modules/types'

export const countdownSchema: ModuleSchemaDef = {
  key: 'countdown',
  name: { es: 'Cuenta regresiva', en: 'Countdown' },
  description: {
    es: 'Temporizador de cuenta regresiva con mensaje de expiración.',
    en: 'Countdown timer with expiration message.',
  },
  version: 1,
  fields: [
    {
      key: 'title',
      type: 'text',
      label: { es: 'Título (opcional)', en: 'Title (optional)' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 100 },
      order: 1,
    },
    {
      key: 'subtitle',
      type: 'text',
      label: { es: 'Subtítulo (opcional)', en: 'Subtitle (optional)' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 200 },
      order: 2,
    },
    {
      key: 'target_date',
      type: 'date',
      label: { es: 'Fecha objetivo', en: 'Target date' },
      description: {
        es: 'Fecha y hora en que termina la cuenta regresiva (ISO 8601).',
        en: 'Date and time when the countdown ends (ISO 8601).',
      },
      isMultilingual: false,
      required: true,
      order: 3,
    },
    {
      key: 'expired_message',
      type: 'textarea',
      label: { es: 'Mensaje al expirar', en: 'Expired message' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 300 },
      order: 4,
    },
    {
      key: 'expired_action_url',
      type: 'link',
      label: { es: 'URL del botón al expirar', en: 'Expired button URL' },
      isMultilingual: false,
      required: false,
      order: 5,
    },
    {
      key: 'expired_action_label',
      type: 'text',
      label: { es: 'Texto del botón al expirar', en: 'Expired button label' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 60 },
      order: 6,
    },
    {
      key: 'show_days',
      type: 'boolean',
      label: { es: 'Mostrar días', en: 'Show days' },
      isMultilingual: false,
      required: false,
      defaultValue: true,
      order: 7,
    },
    {
      key: 'show_hours',
      type: 'boolean',
      label: { es: 'Mostrar horas', en: 'Show hours' },
      isMultilingual: false,
      required: false,
      defaultValue: true,
      order: 8,
    },
    {
      key: 'show_minutes',
      type: 'boolean',
      label: { es: 'Mostrar minutos', en: 'Show minutes' },
      isMultilingual: false,
      required: false,
      defaultValue: true,
      order: 9,
    },
    {
      key: 'show_seconds',
      type: 'boolean',
      label: { es: 'Mostrar segundos', en: 'Show seconds' },
      isMultilingual: false,
      required: false,
      defaultValue: true,
      order: 10,
    },
    {
      key: 'days_label',
      type: 'text',
      label: { es: 'Etiqueta de días', en: 'Days label' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 20 },
      order: 11,
    },
    {
      key: 'hours_label',
      type: 'text',
      label: { es: 'Etiqueta de horas', en: 'Hours label' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 20 },
      order: 12,
    },
    {
      key: 'minutes_label',
      type: 'text',
      label: { es: 'Etiqueta de minutos', en: 'Minutes label' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 20 },
      order: 13,
    },
    {
      key: 'seconds_label',
      type: 'text',
      label: { es: 'Etiqueta de segundos', en: 'Seconds label' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 20 },
      order: 14,
    },
  ],
}
