import type { ModuleSchemaDef } from '@/lib/modules/types'

export const teamSchema: ModuleSchemaDef = {
  key: 'team',
  name: { es: 'Equipo', en: 'Team' },
  description: {
    es: 'Grid de miembros del equipo con foto, rol, bio y redes sociales.',
    en: 'Team members grid with photo, role, bio and social links.',
  },
  version: 1,
  fields: [
    {
      key: 'title',
      type: 'text',
      label: { es: 'Título', en: 'Title' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 100 },
      order: 1,
    },
    {
      key: 'subtitle',
      type: 'text',
      label: { es: 'Subtítulo', en: 'Subtitle' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 200 },
      order: 2,
    },
    {
      key: 'layout',
      type: 'select',
      label: { es: 'Disposición', en: 'Layout' },
      isMultilingual: false,
      required: false,
      defaultValue: 'grid',
      selectOptions: [
        { value: 'grid', label: { es: 'Cuadrícula', en: 'Grid' } },
        { value: 'centered', label: { es: 'Centrado', en: 'Centered' } },
      ],
      order: 3,
    },
    {
      key: 'columns',
      type: 'select',
      label: { es: 'Columnas', en: 'Columns' },
      isMultilingual: false,
      required: false,
      defaultValue: '3',
      selectOptions: [
        { value: '2', label: { es: '2 columnas', en: '2 columns' } },
        { value: '3', label: { es: '3 columnas', en: '3 columns' } },
        { value: '4', label: { es: '4 columnas', en: '4 columns' } },
      ],
      order: 4,
    },
    {
      key: 'members',
      type: 'list',
      label: { es: 'Miembros del equipo', en: 'Team members' },
      description: {
        es: 'Lista de integrantes del equipo a mostrar.',
        en: 'List of team members to display.',
      },
      isMultilingual: false,
      required: true,
      order: 5,
      listItemSchema: [
        {
          key: 'id',
          type: 'text',
          label: { es: 'ID único', en: 'Unique ID' },
          isMultilingual: false,
          required: true,
        },
        {
          key: 'name',
          type: 'text',
          label: { es: 'Nombre completo', en: 'Full name' },
          isMultilingual: false,
          required: true,
        },
        {
          key: 'role',
          type: 'text',
          label: { es: 'Rol / Cargo', en: 'Role / Position' },
          isMultilingual: true,
          required: true,
        },
        {
          key: 'bio',
          type: 'textarea',
          label: { es: 'Biografía corta', en: 'Short bio' },
          isMultilingual: true,
          required: false,
          validation: { maxLength: 300 },
        },
        {
          key: 'avatar_url',
          type: 'image',
          label: { es: 'Foto / Avatar', en: 'Photo / Avatar' },
          isMultilingual: false,
          required: false,
        },
        {
          key: 'social',
          type: 'list',
          label: { es: 'Redes sociales', en: 'Social links' },
          isMultilingual: false,
          required: false,
          listItemSchema: [
            {
              key: 'twitter',
              type: 'link',
              label: { es: 'Twitter / X URL', en: 'Twitter / X URL' },
              isMultilingual: false,
              required: false,
            },
            {
              key: 'linkedin',
              type: 'link',
              label: { es: 'LinkedIn URL', en: 'LinkedIn URL' },
              isMultilingual: false,
              required: false,
            },
            {
              key: 'github',
              type: 'link',
              label: { es: 'GitHub URL', en: 'GitHub URL' },
              isMultilingual: false,
              required: false,
            },
            {
              key: 'instagram',
              type: 'link',
              label: { es: 'Instagram URL', en: 'Instagram URL' },
              isMultilingual: false,
              required: false,
            },
            {
              key: 'website',
              type: 'link',
              label: { es: 'Sitio web personal', en: 'Personal website' },
              isMultilingual: false,
              required: false,
            },
          ],
        },
      ],
    },
  ],
}
