import type { ModuleSchemaDef } from '@/lib/modules/types'

export const gallerySchema: ModuleSchemaDef = {
  key: 'gallery',
  name: { es: 'Galería', en: 'Gallery' },
  description: {
    es: 'Grid de imágenes con lightbox interactivo.',
    en: 'Image grid with interactive lightbox.',
  },
  version: 1,
  fields: [
    {
      key: 'title',
      type: 'text',
      label: { es: 'Título (opcional)', en: 'Title (optional)' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 100 },
      order: 1,
    },
    {
      key: 'subtitle',
      type: 'text',
      label: { es: 'Subtítulo (opcional)', en: 'Subtitle (optional)' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 200 },
      order: 2,
    },
    {
      key: 'layout',
      type: 'select',
      label: { es: 'Tipo de layout', en: 'Layout type' },
      isMultilingual: false,
      required: false,
      defaultValue: 'grid',
      selectOptions: [
        { value: 'grid', label: { es: 'Cuadrícula uniforme', en: 'Uniform grid' } },
        { value: 'masonry', label: { es: 'Mampostería', en: 'Masonry' } },
      ],
      order: 3,
    },
    {
      key: 'columns',
      type: 'select',
      label: { es: 'Número de columnas', en: 'Number of columns' },
      isMultilingual: false,
      required: false,
      defaultValue: '3',
      selectOptions: [
        { value: '2', label: { es: '2 columnas', en: '2 columns' } },
        { value: '3', label: { es: '3 columnas', en: '3 columns' } },
        { value: '4', label: { es: '4 columnas', en: '4 columns' } },
      ],
      order: 4,
    },
    {
      key: 'show_captions',
      type: 'boolean',
      label: { es: 'Mostrar subtítulos', en: 'Show captions' },
      isMultilingual: false,
      required: false,
      defaultValue: true,
      order: 5,
    },
    {
      key: 'images',
      type: 'list',
      label: { es: 'Imágenes', en: 'Images' },
      description: {
        es: 'Lista de imágenes de la galería.',
        en: 'Gallery image list.',
      },
      isMultilingual: false,
      required: true,
      order: 6,
      listItemSchema: [
        {
          key: 'id',
          type: 'text',
          label: { es: 'ID único', en: 'Unique ID' },
          isMultilingual: false,
          required: true,
        },
        {
          key: 'url',
          type: 'image',
          label: { es: 'URL de imagen', en: 'Image URL' },
          isMultilingual: false,
          required: true,
        },
        {
          key: 'alt',
          type: 'text',
          label: { es: 'Texto alternativo', en: 'Alt text' },
          isMultilingual: true,
          required: true,
        },
        {
          key: 'caption',
          type: 'text',
          label: { es: 'Pie de foto (opcional)', en: 'Caption (optional)' },
          isMultilingual: true,
          required: false,
        },
        {
          key: 'category',
          type: 'text',
          label: { es: 'Categoría (opcional)', en: 'Category (optional)' },
          isMultilingual: false,
          required: false,
        },
      ],
    },
  ],
}
