import type { ModuleSchemaDef } from '@/lib/modules/types'

export const pricingSchema: ModuleSchemaDef = {
  key: 'pricing',
  name: { es: 'Precios', en: 'Pricing' },
  description: {
    es: 'Tabla de planes y precios con toggle mensual/anual.',
    en: 'Plans and pricing table with monthly/annual toggle.',
  },
  version: 1,
  fields: [
    {
      key: 'title',
      type: 'text',
      label: { es: 'Título', en: 'Title' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 100 },
      order: 1,
    },
    {
      key: 'subtitle',
      type: 'text',
      label: { es: 'Subtítulo', en: 'Subtitle' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 200 },
      order: 2,
    },
    {
      key: 'toggle_monthly_label',
      type: 'text',
      label: { es: 'Etiqueta toggle Mensual', en: 'Monthly toggle label' },
      isMultilingual: true,
      required: false,
      defaultValue: { es: 'Mensual', en: 'Monthly' },
      order: 3,
    },
    {
      key: 'toggle_annual_label',
      type: 'text',
      label: { es: 'Etiqueta toggle Anual', en: 'Annual toggle label' },
      isMultilingual: true,
      required: false,
      defaultValue: { es: 'Anual', en: 'Annual' },
      order: 4,
    },
    {
      key: 'annual_savings_label',
      type: 'text',
      label: { es: 'Texto de ahorro anual', en: 'Annual savings label' },
      isMultilingual: true,
      required: false,
      defaultValue: { es: 'Ahorra 20%', en: 'Save 20%' },
      order: 5,
    },
    {
      key: 'plans',
      type: 'list',
      label: { es: 'Planes', en: 'Plans' },
      description: {
        es: 'Lista de planes de precios a mostrar.',
        en: 'List of pricing plans to display.',
      },
      isMultilingual: false,
      required: true,
      order: 6,
      listItemSchema: [
        {
          key: 'id',
          type: 'text',
          label: { es: 'ID único', en: 'Unique ID' },
          isMultilingual: false,
          required: true,
        },
        {
          key: 'name',
          type: 'text',
          label: { es: 'Nombre del plan', en: 'Plan name' },
          isMultilingual: true,
          required: true,
        },
        {
          key: 'description',
          type: 'text',
          label: { es: 'Descripción corta', en: 'Short description' },
          isMultilingual: true,
          required: false,
        },
        {
          key: 'price_monthly',
          type: 'number',
          label: { es: 'Precio mensual', en: 'Monthly price' },
          isMultilingual: false,
          required: true,
          validation: { min: 0 },
        },
        {
          key: 'price_annual',
          type: 'number',
          label: { es: 'Precio anual', en: 'Annual price' },
          isMultilingual: false,
          required: true,
          validation: { min: 0 },
        },
        {
          key: 'currency',
          type: 'text',
          label: { es: 'Símbolo de moneda', en: 'Currency symbol' },
          isMultilingual: false,
          required: true,
          defaultValue: '$',
        },
        {
          key: 'period_monthly',
          type: 'text',
          label: { es: 'Texto período mensual', en: 'Monthly period text' },
          isMultilingual: true,
          required: true,
        },
        {
          key: 'period_annual',
          type: 'text',
          label: { es: 'Texto período anual', en: 'Annual period text' },
          isMultilingual: true,
          required: true,
        },
        {
          key: 'is_highlighted',
          type: 'boolean',
          label: { es: '¿Plan destacado?', en: 'Highlighted plan?' },
          isMultilingual: false,
          required: false,
          defaultValue: false,
        },
        {
          key: 'badge',
          type: 'text',
          label: { es: 'Badge (ej: Más popular)', en: 'Badge (e.g., Most popular)' },
          isMultilingual: true,
          required: false,
        },
        {
          key: 'cta_label',
          type: 'text',
          label: { es: 'Texto del botón CTA', en: 'CTA button text' },
          isMultilingual: true,
          required: true,
        },
        {
          key: 'cta_url',
          type: 'link',
          label: { es: 'URL del botón CTA', en: 'CTA button URL' },
          isMultilingual: false,
          required: true,
        },
        {
          key: 'features',
          type: 'list',
          label: { es: 'Características', en: 'Features' },
          isMultilingual: false,
          required: true,
          listItemSchema: [
            {
              key: 'id',
              type: 'text',
              label: { es: 'ID único', en: 'Unique ID' },
              isMultilingual: false,
              required: true,
            },
            {
              key: 'text',
              type: 'text',
              label: { es: 'Descripción', en: 'Description' },
              isMultilingual: true,
              required: true,
            },
            {
              key: 'included',
              type: 'boolean',
              label: { es: '¿Incluida?', en: 'Included?' },
              isMultilingual: false,
              required: true,
              defaultValue: true,
            },
          ],
        },
      ],
    },
  ],
}
