import type { ModuleSchemaDef } from '@/lib/modules/types'

export const finalCtaSchema: ModuleSchemaDef = {
  key: 'final_cta',
  name: { es: 'CTA final', en: 'Final CTA' },
  description: {
    es: 'Sección de llamada a la acción final con fondo llamativo y botones de conversión.',
    en: 'Final call-to-action section with a striking background and conversion buttons.',
  },
  version: 1,
  fields: [
    {
      key: 'title',
      type: 'text',
      label: { es: 'Título', en: 'Title' },
      description: {
        es: 'Frase principal de impacto.',
        en: 'Main impact phrase.',
      },
      isMultilingual: true,
      required: true,
      validation: { minLength: 3, maxLength: 120 },
      order: 1,
    },
    {
      key: 'subtitle',
      type: 'text',
      label: { es: 'Subtítulo', en: 'Subtitle' },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 200 },
      order: 2,
    },
    {
      key: 'description',
      type: 'textarea',
      label: { es: 'Descripción', en: 'Description' },
      description: {
        es: 'Texto adicional de apoyo.',
        en: 'Additional supporting text.',
      },
      isMultilingual: true,
      required: false,
      validation: { maxLength: 400 },
      order: 3,
    },
    {
      key: 'primaryButton.label',
      type: 'text',
      label: { es: 'Botón primario — texto', en: 'Primary button — text' },
      isMultilingual: true,
      required: true,
      group: 'buttons',
      order: 4,
    },
    {
      key: 'primaryButton.url',
      type: 'link',
      label: { es: 'Botón primario — URL', en: 'Primary button — URL' },
      isMultilingual: false,
      required: true,
      group: 'buttons',
      order: 5,
    },
    {
      key: 'secondaryButton.label',
      type: 'text',
      label: { es: 'Botón secundario — texto', en: 'Secondary button — text' },
      isMultilingual: true,
      required: false,
      group: 'buttons',
      order: 6,
    },
    {
      key: 'secondaryButton.url',
      type: 'link',
      label: { es: 'Botón secundario — URL', en: 'Secondary button — URL' },
      isMultilingual: false,
      required: false,
      group: 'buttons',
      order: 7,
    },
    {
      key: 'backgroundStyle',
      type: 'select',
      label: { es: 'Estilo de fondo', en: 'Background style' },
      isMultilingual: false,
      required: false,
      defaultValue: 'gradient',
      selectOptions: [
        { value: 'gradient', label: { es: 'Degradado', en: 'Gradient' } },
        { value: 'solid', label: { es: 'Color sólido', en: 'Solid color' } },
        { value: 'transparent', label: { es: 'Transparente', en: 'Transparent' } },
      ],
      order: 8,
    },
  ],
}
